### ISSUE TITLE
[BUG] Adding new User with /user endpoint fails

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-api#194]
## Description

When trying to create a new user with POST call to /user endpoint kernelci-api crashes.

## Steps to reproduce

- Run kernelci-api instance with the code from the `main` branch
- Create admin user with [create_admin_user](https://github.com/kernelci/kernelci-api/blob/main/create_admin_user) script
- Create API token for admin user 
- Try to create new (non-admin) user

```bash
curl -X 'POST' \
  'http://localhost:9001/user/new_user' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer ADMIN_TOKEN' \
  -d '{"password": "secret"}'
```

### Expected result

New user is created.

### Actual result

Request returns `HTTP 500` with a following Traceback visible in the logs

```
today at 2:12:56 PMERROR:    Exception in ASGI application
today at 2:12:56 PMTraceback (most recent call last):
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
today at 2:12:56 PM    result = await app(self.scope, self.receive, self.send)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
today at 2:12:56 PM    return await self.app(scope, receive, send)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/fastapi/applications.py", line 208, in __call__
today at 2:12:56 PM    await super().__call__(scope, receive, send)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
today at 2:12:56 PM    await self.middleware_stack(scope, receive, send)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
today at 2:12:56 PM    raise exc from None
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
today at 2:12:56 PM    await self.app(scope, receive, _send)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
today at 2:12:56 PM    raise exc from None
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
today at 2:12:56 PM    await self.app(scope, receive, sender)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/starlette/routing.py", line 580, in __call__
today at 2:12:56 PM    await route.handle(scope, receive, send)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/starlette/routing.py", line 241, in handle
today at 2:12:56 PM    await self.app(scope, receive, send)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/starlette/routing.py", line 52, in app
today at 2:12:56 PM    response = await func(request)
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/fastapi/routing.py", line 226, in app
today at 2:12:56 PM    raw_response = await run_endpoint_function(
today at 2:12:56 PM  File "/home/kernelci/.local/lib/python3.10/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
today at 2:12:56 PM    return await dependant.call(**values)
today at 2:12:56 PM  File "/home/kernelci/./api/main.py", line 103, in post_user
today at 2:12:56 PM    obj = await db.create(User(
today at 2:12:56 PM  File "/home/kernelci/./api/db.py", line 100, in create
today at 2:12:56 PM    obj.set_timeout()
today at 2:12:56 PMAttributeError: 'User' object has no attribute 'set_timeout'
```

**Comment by mgalka** [comment]
It looks that changes from commit https://github.com/kernelci/kernelci-api/commit/98db8b3f90620c1416104be6752f7ad231c9fdaf work only for `Node` objects.
